#!/usr/bin/env python3
"""Curriculum controller: train ONE body-conditioned policy, no teachers.

Terminology (grounded in the env's config keys):
  source S = `dataSub`       — whose mocap MOTION is replayed as the reference.
  body   B = `subjectBodies`  — whose body MORPHOLOGY the policy controls.
  pair  S->B                  — drive body B using motion S. Identity when S==B.
(The weights-file key is `b{B}_s{S}` only because that mirrors the env's weight
tensor layout, row=body/col=motion — it carries no semantic priority.)

Folds OMOMO subjects in one at a time, resuming the previous checkpoint each
step, so a single network gradually learns to drive every body from every
source's motions. Held-out subjects ({4,10,16}) never enter. How a newly added
subject's pairs are introduced is set by --schedule:

  coarse                  — the whole subject lands at once: every pair in the
                            new active set (both directions) goes live in one
                            stage. The original behavior.
  identity-source-target  — each new subject N is folded over THREE sub-stages,
                            keeping all already-live pairs active throughout:
                              a) identity:  add  N -> N
                              b) as source: add  N -> bExisting
                              c) as target: add  sExisting -> N
                            The anchor subject gets only the identity sub-stage.

Sub-staging is implemented as a WEIGHT MASK: subjectBodies/dataSub always hold
the full active set, and the weights file carries 0 for not-yet-live pairs (so
torch.multinomial never samples them) and a positive weight for live ones. No
env change is needed beyond the existing subjectPairWeightsFile support.

Two pieces of automation (no human in the loop):

1. Plateau-triggered advancement. The controller launches a normal
   `intermimic.run` training subprocess, parses its `epoch_num:N mean_rewards:[X]`
   stdout, and advances to the next sub-stage once reward stops improving by
   more than `--improve-frac` for `--patience` epochs (after `--min-epochs`).
   This absorbs the reward dip that follows each new sub-stage. The cheap cross
   phases (source, target) get min-epochs/patience/stage-max divided by
   `--cross-epoch-divisor` (default 3); identity and coarse 'full' stages keep
   the full budget — this trims the "floor tax" of the many small sub-stages.

2. Pair balancing (--balance). Balancing is per (source, body) PAIR, not per
   subject. With `inverse-exposure` each sub-stage writes weights proportional
   to 1/(exposure so far) over the LIVE pairs, so freshly added pairs (zero
   exposure) get the most sampling and lifetime exposure equalizes across pairs.
   With `uniform` no weights file is written at all, so pairs are sampled
   uniformly at random (only valid with --schedule coarse — sub-staging needs
   the mask). Note: a pair is only reachable if some env physically owns a
   shared object — the env prints a WARNING listing any unreachable pairs.
   `--exposure` controls how the exposure feeding those weights is tracked:
   `estimated` (epochs * normalized weight) or `measured` (the env counts the
   ACTUAL (source,body) samples per sub-stage and the controller reweights from
   true counts AND reports leaks — masked pairs the fallback still drew).

Run (normally inside one slurm job holding one GPU):
  # experimental: sub-staged fold-in with inverse-exposure balancing
  python scripts/curriculum_runner.py --run-name ist
  # baseline: whole subject at once, plain random pair sampling
  python scripts/curriculum_runner.py --run-name baseline --schedule coarse --balance uniform
Validate config generation without launching training:
  python scripts/curriculum_runner.py --run-name ist --dry-run
"""
import argparse
import json
import os
import re
import signal
import subprocess
import sys
import time
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]

# Fold-in order over the 14 train subjects. sub2 anchors the identity prior;
# the three women {1,9,15} are interleaved early so the policy isn't trained on
# only male bodies for long. Held-out {4,10,16} are absent on purpose.
DEFAULT_ORDER = [2, 3, 9, 17, 5, 1, 7, 11, 15, 6, 8, 12, 13, 14]
HELD_OUT = [4, 10, 16]

# Reward line emitted every epoch by intermimic_agent.py, e.g.
#   epoch_num:19 mean_rewards:[3.26] fps step: 16793.9 fps total: 14131.5
REWARD_RX = re.compile(r"epoch_num:(\d+)\s+mean_rewards:\[?\s*([-\d.eE+]+)")

ENV_TMPL = """\
# AUTO-GENERATED by scripts/curriculum_runner.py — curriculum substage {stage}.
# Single body-conditioned policy, no teachers. Active subjects (body & source):
#   {active}
# Per-(source,body) sampling weights (or uniform) — see line below.
env:
  numEnvs: {num_envs}
  envSpacing: 2
  episodeLength: 300
  isFlagrun: False
  enableDebugVis: False
  playdataset: False
  projtype: "None"
  saveImages: False
  initVel: False
  moreRigid: False
  pdControl: True
  powerScale: 1.0
  controlFrequencyInv: 2
  stateInit: "Hybrid"
  rolloutLength: 300
  hybridInitProb: 0.1
  dataFPS: 30
  dataFramesScale: 1
  dataSub: {datasub}
  subjectBodies: {bodies}
  betas_file: {betas_file}
  bodyNormalizedReward: {body_norm}
{heights_line}
{pair_weights_line}
{counts_line}
  ballSize: 1.
  numObs: {num_obs}
  useTransformerObs: {use_transformer_obs}
  motion_file: InterAct/OMOMO_new
  robotType: "smplx/omomo.xml"
  objectDensity: 200
  localRootObs: False
  keyBodies: ["L_Hip", "L_Knee", "L_Ankle", "L_Toe", "R_Hip", "R_Knee", "R_Ankle", "R_Toe", "Torso", "Spine", "Chest", "Neck", "Head", "L_Thorax", "L_Shoulder", "L_Elbow", "L_Wrist", "R_Thorax", "R_Shoulder", "R_Elbow", "R_Wrist"]
  contactBodies: ["L_Hip", "L_Knee", "L_Ankle", "L_Toe", "R_Hip", "R_Knee", "R_Ankle", "R_Toe", "Torso", "Spine", "Chest", "Neck", "Head", "L_Thorax", "L_Shoulder", "L_Elbow", "L_Wrist", "R_Thorax", "R_Shoulder", "R_Elbow", "R_Wrist", "L_Index3", "L_Middle3", "L_Pinky3", "L_Ring3","L_Thumb3","R_Index3", "R_Middle3", "R_Pinky3", "R_Ring3","R_Thumb3"]
  terminationHeight: 0.15
  enableEarlyTermination: True
  physicalBufferSize: 3
  maskDeadEnvs: {mask_dead_envs}

  asset:
    assetRoot: "intermimic/data/assets"

  plane:
    staticFriction: 0.9
    dynamicFriction: 0.9
    restitution: 0.7

  rewardWeights:
    p: 30.
    r: 2.5
    pv: 0.
    rv: 0.
    op: 5.0
    or: 0.1
    opv: 0.1
    orv: 0.
    ig: 5.
    cg_hand: 5.
    cg_other: 5.
    cg_all: 3.
    eg1: 0.00002
    eg2: 0.00002
    eg3: 0.000000001

sim:
  substeps: 2
  physx:
    num_threads: 4
    solver_type: 1
    num_position_iterations: 4
    num_velocity_iterations: 1
    contact_offset: 0.02
    rest_offset: 0.0
    bounce_threshold_velocity: 0.2
    max_depenetration_velocity: 100.0
    default_buffer_size_multiplier: 20.0
    max_gpu_contact_pairs: 34603008

  flex:
    num_inner_iterations: 10
    warm_start: 0.25
"""

TRAIN_TMPL = """\
params:
  seed: -1

  algo:
    name: intermimic

  model:
    name: intermimic

  network:
    name: {network_name}
    separate: True

    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: -2.9
        fixed_sigma: True
        learn_sigma: False

    mlp:
      units: [1024, 1024, 512]
      activation: relu
      d2rl: False

      initializer:
        name: default
      regularizer:
        name: None

  load_checkpoint: False

  config:
    name: mimic
    # AUTO-GENERATED curriculum substage {stage}: active subjects {active}
    full_experiment_name: {exp_name}
    env_name: rlgpu
    multi_gpu: False
    ppo: True
    mixed_precision: False
    normalize_input: True
    normalize_value: False
    reward_shaper:
      scale_value: 1
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 2e-5
    lr_schedule: constant
    score_to_win: 20000
    max_epochs: 100000
    save_best_after: 100
    save_frequency: {save_frequency}
    print_stats: True
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: False
    ppo: True
    e_clip: 0.2
    horizon_length: 32
    minibatch_size: 16384
    mini_epochs: 6
    critic_coef: 5
    clip_value: False
    seq_len: 4
    bounds_loss_coef: 10
    enable_eps_greedy: False
    save_intermediate: True
    mask_dead_envs: {mask_dead_envs}
    resume_from: {resume_from}
"""


def yaml_sub_list(subjects):
    """['sub2', 'sub3'] formatting for a list of subject ints."""
    return "[" + ", ".join(f"'sub{n}'" for n in subjects) + "]"


def compute_pair_weights(bodies, sources, live, exposure, eps=1.0):
    """Per (source, body) pair weight: inverse-exposure for live, 0 otherwise.

    `bodies` and `sources` are usually the same active set, but differ when
    target-only synthetic bodies are folded in (they appear as bodies, never as
    sources). `live` is the set of (s, b) tuples currently allowed to be
    sampled. Live pairs get weight ∝ 1/(exposure + eps), normalized to mean 1
    over the live set (scale is irrelevant to multinomial sampling but keeps
    numbers readable). Not-yet-live pairs are written as an explicit 0.0 — the
    env defaults a MISSING key to 1.0, so we must emit the zero to mask them
    out. Keys are 'b{B}_s{S}' to match what the env reads (body-first layout).
    """
    w, live_vals = {}, {}
    for b in bodies:
        for s in sources:
            key = f"b{b}_s{s}"
            if (s, b) in live:
                live_vals[key] = 1.0 / (exposure.get(key, 0.0) + eps)
            else:
                w[key] = 0.0  # masked: never sampled this sub-stage
    mean = (sum(live_vals.values()) / len(live_vals)) if live_vals else 1.0
    for k, v in live_vals.items():
        w[k] = v / mean
    return w


def build_substages(order, schedule):
    """Expand the fold-in order into a flat list of sub-stage descriptors.

    Each descriptor carries the cumulative set of LIVE (source, body) pairs at
    that point — already-live pairs persist across sub-stages so the policy
    keeps rehearsing them (anti-forgetting). Fields:
      stage    1-based subject index (which subject is being folded in)
      suffix   unique tag for dirs/filenames, e.g. '03' (coarse) or '03b' (ist)
      phase    'full' | 'identity' | 'source' | 'target'
      new      the subject number being folded in at this sub-stage
      bodies   subjectBodies for the env (full active set)
      sources  dataSub for the env (full active set)
      live     set of (s, b) tuples allowed to be sampled (the weight mask)
    """
    subs, live = [], set()
    for st, n in enumerate(order):
        prev = order[:st]              # subjects already present before N
        active = sorted(order[:st + 1])
        if schedule == "coarse":
            # Whole subject at once: every pair (both directions) goes live.
            for s in active:
                for b in active:
                    live.add((s, b))
            subs.append(dict(stage=st + 1, suffix=f"{st + 1:02d}", phase="full",
                             new=n, bodies=active, sources=active, live=set(live)))
        else:  # identity-source-target
            live.add((n, n))           # a) identity: N -> N
            subs.append(dict(stage=st + 1, suffix=f"{st + 1:02d}a", phase="identity",
                             new=n, bodies=active, sources=active, live=set(live)))
            if prev:
                for b in prev:         # b) as source: N's motion -> existing bodies
                    live.add((n, b))
                subs.append(dict(stage=st + 1, suffix=f"{st + 1:02d}b", phase="source",
                                 new=n, bodies=active, sources=active, live=set(live)))
                for s in prev:         # c) as target: existing motions -> N's body
                    live.add((s, n))
                subs.append(dict(stage=st + 1, suffix=f"{st + 1:02d}c", phase="target",
                                 new=n, bodies=active, sources=active, live=set(live)))
    return subs


def inject_synthetic(real_subs, order, syn_ids, position, mode, batch_size):
    """Fold target-only synthetic bodies into the substage list.

    Synthetic bodies (subject ids >= synthetic-start-id, e.g. sub100..) are
    BODIES the policy controls but never SOURCES -- they're driven by the real
    sources, scored against the real reference (no GT of their own). So their
    live pairs are (real_source, syn_body) only.

    position: 'append'     -> all synthetic stages after the full real curriculum
              'interleave'  -> spread between the real stages (each syn body then
                               pairs only with the real sources live SO FAR, and
                               later real sources retro-pair with it).
    mode:     'staged'      -> one synthetic body per stage (batch_size forced 1)
              'batched'     -> batch_size synthetic bodies per stage
    Returns a new substage list with cumulative live/bodies/sources recomputed.
    """
    if not syn_ids:
        return real_subs
    bs = 1 if mode == "staged" else max(1, batch_size)
    batches = [syn_ids[i:i + bs] for i in range(0, len(syn_ids), bs)]

    # new real pairs introduced at each real substage (cumulative -> per-stage delta)
    real_new, prev = [], set()
    for ss in real_subs:
        real_new.append(ss["live"] - prev)
        prev = ss["live"]

    # which real substage index each batch is inserted AFTER
    after = {}
    n = len(real_subs)
    if position == "append":
        after[n - 1] = list(batches)
    else:  # interleave: evenly spaced across the real stages
        for k, b in enumerate(batches):
            pos = min(n - 1, int((k + 1) * n / (len(batches) + 1)))
            after.setdefault(pos, []).append(b)

    merged, cum, syn_live, real_src = [], set(), [], set()
    syn_n = 0
    for ridx, ss in enumerate(real_subs):
        cum |= real_new[ridx]
        # a newly-live real source retro-pairs with every synthetic body so far
        for s in {s for (s, _) in real_new[ridx]} - real_src:
            real_src.add(s)
            cum |= {(s, syn_b) for syn_b in syn_live}
        merged.append({**ss, "bodies": sorted({b for (_, b) in cum}),
                       "sources": sorted({s for (s, _) in cum}), "live": set(cum)})
        for batch in after.get(ridx, []):
            for syn_b in batch:
                cum |= {(s, syn_b) for s in real_src}   # driven by real sources live so far
                syn_live.append(syn_b)
            syn_n += 1
            merged.append(dict(stage=ss["stage"], suffix=f"y{syn_n:02d}",
                               phase="synthetic", new=batch[0],
                               bodies=sorted({b for (_, b) in cum}),
                               sources=sorted({s for (s, _) in cum}), live=set(cum)))
    return merged


def update_exposure(exposure, active, weights, epochs):
    """Accumulate per-pair exposure ≈ epochs * (this pair's sampling fraction).

    Sampling fraction ≈ normalized weight, so high-weight pairs gain exposure
    fastest — which then lowers their weight next stage. Closes the balancing
    loop toward equal lifetime exposure.
    """
    total = sum(weights.values())
    for key, w in weights.items():
        exposure[key] = exposure.get(key, 0.0) + epochs * (w / total)


def latest_checkpoint(exp_name):
    """Newest complete snapshot checkpoints/<exp>/nn/mimic_<frames>.pth, else mimic.pth."""
    nn = REPO / "checkpoints" / exp_name / "nn"
    if not nn.is_dir():
        return None
    snaps = []
    for p in nn.glob("mimic_*.pth"):
        m = re.search(r"mimic_(\d+)\.pth$", p.name)
        if m:
            snaps.append((int(m.group(1)), p))
    if snaps:
        return max(snaps)[1]
    last = nn / "mimic.pth"
    return last if last.exists() else None


def terminate(proc, grace=20):
    """Stop the training subprocess: SIGTERM, wait, then SIGKILL."""
    if proc.poll() is not None:
        return
    proc.terminate()
    try:
        proc.wait(timeout=grace)
    except subprocess.TimeoutExpired:
        proc.kill()
        proc.wait()


def run_stage(env_cfg, train_cfg, exp_name, log_path, args,
              min_epochs, patience, stage_max_epochs):
    """Launch one sub-stage; return (epochs_run, exited_on_own).

    Streams the training stdout to both log_path and our stdout (so it lands in
    the slurm .out), watches reward, and stops the subprocess on plateau / cap.
    The plateau thresholds (min_epochs, patience, stage_max_epochs) are passed
    in per-sub-stage so cheap cross phases can run on a smaller budget than the
    identity phase; improve_frac still comes from args (it's global).
    """
    cmd = [sys.executable, "-u", "-m", "intermimic.run",
           "--task", "InterMimic",
           "--cfg_env", env_cfg, "--cfg_train", train_cfg,
           "--headless", "--output", "checkpoints"]
    env = os.environ.copy()
    # Mirror what the train shells set so `intermimic` is importable.
    src = str(REPO / "isaacgym" / "src")
    env["PYTHONPATH"] = os.pathsep.join(
        [src, str(REPO), env.get("PYTHONPATH", "")]).strip(os.pathsep)

    print(f"[curriculum] launching: {' '.join(cmd)}", flush=True)
    proc = subprocess.Popen(cmd, cwd=str(REPO), stdout=subprocess.PIPE,
                            stderr=subprocess.STDOUT, text=True, bufsize=1, env=env)

    # rl_games restores epoch_num on warm-start, so the printed epoch counter is
    # CUMULATIVE across stages (stage 2 may start near epoch 3000). All our
    # thresholds are therefore measured relative to this stage's first epoch.
    best, best_epoch = float("-inf"), None
    stage_start_epoch, last_epoch = None, None
    advancing = False
    with open(log_path, "w") as logf:
        for line in proc.stdout:
            logf.write(line)
            sys.stdout.write(line)
            sys.stdout.flush()
            m = REWARD_RX.search(line)
            if not m:
                continue
            ep = int(m.group(1))
            try:
                rew = float(m.group(2))
            except ValueError:
                continue
            if stage_start_epoch is None:
                stage_start_epoch = ep
            last_epoch = ep
            in_stage = ep - stage_start_epoch
            # An "improvement" must beat the best by > improve_frac.
            improved = (rew > best * (1.0 + args.improve_frac)) if best > 0 else (rew > best)
            if improved:
                best, best_epoch = rew, ep
            if in_stage >= min_epochs and (ep - best_epoch) >= patience:
                print(f"[curriculum] PLATEAU {exp_name}: epoch {ep} (+{in_stage} in stage), "
                      f"best {best:.3f}@{best_epoch} (no >{args.improve_frac:.0%} gain in "
                      f"{patience} epochs) -> advance", flush=True)
                advancing = True
                break
            if in_stage >= stage_max_epochs:
                print(f"[curriculum] CAP {exp_name}: +{in_stage} epochs in stage "
                      f"(stage_max_epochs={stage_max_epochs}) -> advance", flush=True)
                advancing = True
                break
    epochs_in_stage = (last_epoch - stage_start_epoch) if stage_start_epoch is not None else 0
    exited_on_own = proc.poll() is not None and not advancing
    terminate(proc)
    return epochs_in_stage, exited_on_own


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--run-name", required=True, help="names the work/output dirs")
    ap.add_argument("--order", type=int, nargs="+", default=DEFAULT_ORDER,
                    help="fold-in order of subject numbers (first = identity prior)")
    ap.add_argument("--num-envs", type=int, default=4096)
    ap.add_argument("--patience", type=int, default=300,
                    help="advance after this many epochs with no >improve-frac gain")
    ap.add_argument("--min-epochs", type=int, default=300,
                    help="never advance before this many epochs in a stage")
    ap.add_argument("--improve-frac", type=float, default=0.01,
                    help="fractional reward gain that counts as improvement")
    ap.add_argument("--stage-max-epochs", type=int, default=8000,
                    help="hard cap per stage if it never plateaus")
    ap.add_argument("--cross-epoch-divisor", type=int, default=3,
                    help="divide min-epochs/patience/stage-max-epochs by this for "
                         "the cheap cross phases (source, target); the identity "
                         "phase (and coarse 'full' stages) keep the full budget. "
                         "Set to 1 to give every phase the same budget.")
    ap.add_argument("--save-frequency", type=int, default=100)
    ap.add_argument("--schedule", choices=["coarse", "identity-source-target"],
                    default="identity-source-target",
                    help="coarse: whole subject lands per stage. "
                         "identity-source-target: per new subject fold identity "
                         "(N->N), then as-source (N->existing), then as-target "
                         "(existing->N).")
    ap.add_argument("--balance", choices=["inverse-exposure", "uniform"],
                    default="inverse-exposure",
                    help="inverse-exposure: weight live pairs by 1/exposure. "
                         "uniform: no weights file, plain random pair sampling "
                         "(only valid with --schedule coarse).")
    ap.add_argument("--exposure", choices=["estimated", "measured"],
                    default="estimated",
                    help="how exposure feeding the inverse-exposure weights is "
                         "tracked. estimated: epochs * normalized-weight heuristic. "
                         "measured: the env counts ACTUAL (source,body) samples and "
                         "the controller reweights from true counts (also reports "
                         "leaks). Ignored when --balance uniform (no weights).")
    ap.add_argument("--mask-dead-envs", action="store_true",
                    help="hard guarantee against pair leaks: zero the PPO gradient "
                         "from envs whose fixed (body,object) has no live pair this "
                         "sub-stage (they'd otherwise fall back to a not-yet-live "
                         "pair). Needs weights, so ignored when --balance uniform.")
    ap.add_argument("--resume", action="store_true",
                    help="resume curriculum from state.json in the run dir")
    ap.add_argument("--dry-run", action="store_true",
                    help="generate all stage configs + weights and exit (no training)")
    ap.add_argument("--no-echo-configs", action="store_false", dest="echo_configs",
                    help="don't dump each substage's full env/train YAML into the log "
                         "(the structured per-substage summary is always printed)")
    ap.add_argument("--network", choices=["mlp", "transformer"], default="mlp",
                    help="policy network. mlp (stock, 2-horizon obs, numObs 3230) "
                         "or transformer (temporal transformer over 4-horizon obs, "
                         "numObs 6524). Same curriculum/fixes either way -- only the "
                         "net + obs layout change, for a fair MLP-vs-transformer test.")
    # Synthetic target-only training bodies (sub<start-id>..). Need matching
    # smplx_omomo_sub<N>.xml + betas entries (use omomo_betas_neutral_aug.npz).
    ap.add_argument("--num-synthetic", type=int, default=0,
                    help="number of synthetic target-only bodies to fold in (0=off)")
    ap.add_argument("--synthetic-start-id", type=int, default=100,
                    help="first synthetic body id; bodies are sub<id>..sub<id+num-1>")
    ap.add_argument("--synthetic-position", choices=["append", "interleave"],
                    default="append",
                    help="append: synthetic stages after the full real curriculum; "
                         "interleave: spread between real stages")
    ap.add_argument("--synthetic-mode", choices=["batched", "staged"], default="batched",
                    help="batched: --synthetic-batch-size bodies per stage; "
                         "staged: one body per stage")
    ap.add_argument("--synthetic-batch-size", type=int, default=5)
    ap.add_argument("--final-train-epochs", type=int, default=0,
                    help="after ALL data is folded in, keep training on the full set "
                         "with NO early plateau-stop. -1 = UNBOUNDED (train until the "
                         "slurm time limit, no epoch cap); N>0 = stop after N more "
                         "epochs; 0 = stop at the last substage (old behavior).")
    ap.add_argument("--body-norm-reward", action="store_true",
                    help="height-normalize the pose-error reward (removes body-size "
                         "bias). Synthetic bodies need a --subject-heights-file.")
    ap.add_argument("--subject-heights-file", default=None,
                    help="JSON {subject_id: height_m} extending SUBJECT_HEIGHTS, for "
                         "synthetic bodies (sub100+) under --body-norm-reward")
    ap.add_argument("--betas-file", default="scripts/omomo_betas.npz",
                    help="SMPL-X betas file for body conditioning. Default = stock "
                         "GENDERED betas. Use scripts/omomo_betas_neutral.npz for the "
                         "shared-neutral-space conditioning experiment (bodies/MJCFs "
                         "and ground-truth motion are UNCHANGED -- only the 32 betas "
                         "obs dims switch to a coherent cross-gender descriptor).")
    args = ap.parse_args()

    os.chdir(REPO)  # so all repo-relative paths resolve
    order = args.order
    assert not (set(order) & set(HELD_OUT)), \
        f"fold order must not include held-out subjects {HELD_OUT}"

    # Echo the full invocation + settings up front so every run's log is
    # self-describing -- you can always reconstruct exactly what was launched.
    # Network selection: stock MLP vs the temporal transformer (4-horizon obs).
    is_transformer = args.network == "transformer"
    network_name = "intermimic_transformer" if is_transformer else "intermimic"
    use_transformer_obs = "true" if is_transformer else "false"
    num_obs = 6524 if is_transformer else 3230
    body_norm = "true" if args.body_norm_reward else "false"
    heights_line = (f"  subjectHeightsFile: {args.subject_heights_file}"
                    if args.subject_heights_file else
                    "  # subjectHeightsFile omitted (SUBJECT_HEIGHTS dict only)")
    print(f"[curriculum] invocation: {' '.join(sys.argv)}", flush=True)
    print(f"[curriculum] settings: run={args.run_name} schedule={args.schedule} "
          f"balance={args.balance} exposure={args.exposure} "
          f"mask_dead_envs={args.mask_dead_envs} num_envs={args.num_envs} "
          f"cross_epoch_divisor={args.cross_epoch_divisor} "
          f"network={args.network}(numObs={num_obs}) order={order}", flush=True)

    # Sub-staging masks not-yet-live pairs via a weights file; plain uniform
    # sampling can't express that, so force weights on whenever we sub-stage.
    use_weights = args.balance == "inverse-exposure" or args.schedule != "coarse"
    if args.balance == "uniform" and args.schedule != "coarse":
        print(f"[curriculum] NOTE: --schedule {args.schedule} needs a weights file "
              f"to mask not-yet-live pairs; overriding --balance uniform -> "
              f"inverse-exposure.", flush=True)
    if args.mask_dead_envs and not use_weights:
        print("[curriculum] NOTE: --mask-dead-envs needs pair weights to know which "
              "pairs are live; it is a no-op under --balance uniform.", flush=True)

    substages = build_substages(order, args.schedule)
    if args.num_synthetic > 0:
        syn_ids = list(range(args.synthetic_start_id,
                             args.synthetic_start_id + args.num_synthetic))
        substages = inject_synthetic(substages, order, syn_ids,
                                     args.synthetic_position, args.synthetic_mode,
                                     args.synthetic_batch_size)
        print(f"[curriculum] +{args.num_synthetic} synthetic bodies "
              f"(sub{syn_ids[0]}..sub{syn_ids[-1]}) {args.synthetic_position}/"
              f"{args.synthetic_mode} -> {len(substages)} total substages", flush=True)
    # Final converge stage: same full live set as the last substage, but trained
    # long (no plateau-stop) so the policy actually converges on the complete data.
    if args.final_train_epochs != 0 and substages:
        last = substages[-1]
        substages.append(dict(stage=last["stage"], suffix="final", phase="final",
                              new=last["new"], bodies=last["bodies"],
                              sources=last["sources"], live=set(last["live"])))
        cap = ("UNBOUNDED (until slurm time limit)" if args.final_train_epochs < 0
               else f"up to {args.final_train_epochs} epochs")
        print(f"[curriculum] + final converge stage on the full set, {cap}, "
              f"NO plateau-stop", flush=True)

    work = REPO / "curriculum_work" / args.run_name
    cfgdir = work / "cfgs"
    cfgdir.mkdir(parents=True, exist_ok=True)
    state_path = work / "state.json"

    exposure, start_idx, prev_ckpt = {}, 0, None
    if args.resume and state_path.exists():
        st = json.loads(state_path.read_text())
        exposure = st["exposure"]
        start_idx = st["next_substage"]
        prev_ckpt = st.get("last_ckpt")
        print(f"[curriculum] resuming at substage {start_idx}; last_ckpt={prev_ckpt}", flush=True)

    def rel(p):
        return str(Path(p).relative_to(REPO))

    def exp_name_of(ss):
        return (f"smplx_curriculum_{args.run_name}_s{ss['suffix']}"
                f"_sub{ss['new']}_{ss['phase']}")

    for idx in range(start_idx if not args.dry_run else 0, len(substages)):
        ss = substages[idx]
        active = ss["bodies"]           # bodies == sources == full active set
        exp_name = exp_name_of(ss)
        env_cfg = cfgdir / f"env_s{ss['suffix']}.yaml"
        train_cfg = cfgdir / f"train_s{ss['suffix']}.yaml"

        # Per-phase plateau budget: the cheap cross phases (source, target) get
        # min-epochs/patience/stage-max divided by --cross-epoch-divisor; the
        # identity phase and coarse 'full' stages keep the full budget. The cap
        # is floored at min_e+pat so it can never fire before a plateau is even
        # possible.
        if ss['phase'] == 'final':
            # never plateau-stop; -1 => no epoch cap at all (run to the slurm timeout).
            min_e = 1
            pat = smax = (float('inf') if args.final_train_epochs < 0
                          else args.final_train_epochs)
        else:
            div = args.cross_epoch_divisor if ss['phase'] in ('source', 'target') else 1
            min_e = max(1, args.min_epochs // div)
            pat = max(1, args.patience // div)
            smax = max(min_e + pat, args.stage_max_epochs // div)

        # Pair weights: inverse-exposure over live pairs, 0 for masked ones.
        # Skipped entirely for the uniform baseline (plain random sampling).
        weights = weights_file = None
        if use_weights:
            weights = compute_pair_weights(ss["bodies"], ss["sources"], ss["live"], exposure)
            weights_file = cfgdir / f"weights_s{ss['suffix']}.json"
            weights_file.write_text(json.dumps(weights, indent=2, sort_keys=True))
            pair_weights_line = f"  subjectPairWeightsFile: {rel(weights_file)}"
        else:
            pair_weights_line = "  # subjectPairWeightsFile omitted: uniform pair sampling"

        # Realized-sample counting: only meaningful when we have weights (the env
        # counter needs them) and the user asked for measured exposure.
        use_counts = use_weights and args.exposure == "measured"
        if use_counts:
            counts_file = cfgdir / f"counts_s{ss['suffix']}.json"
            counts_line = f"  pairSampleCountsFile: {rel(counts_file)}"
        else:
            counts_file = None
            counts_line = "  # pairSampleCountsFile omitted: estimated exposure"

        # Dead-env gradient masking needs the weights (to know which pairs are
        # live); meaningless without them, so it rides with use_weights.
        mask_dead = args.mask_dead_envs and use_weights

        # Warm-start chain, with a twist for --resume: if this sub-stage was
        # interrupted mid-flight it already has its own snapshots, so continue
        # from the newest of THOSE rather than restarting from the previous
        # sub-stage (caveat D fix). A fresh sub-stage has no such dir yet.
        inflight = None if args.dry_run else latest_checkpoint(exp_name)
        if inflight is not None:
            resume_from = rel(inflight)
            print(f"[curriculum] substage {idx + 1} resuming from its own in-flight "
                  f"checkpoint {rel(inflight)}", flush=True)
        elif idx == 0 and not prev_ckpt:
            resume_from = "'None'"          # cold start: identity prior from scratch
        elif prev_ckpt:
            resume_from = rel(prev_ckpt)    # warm-start from previous sub-stage
        else:
            # dry-run: no real checkpoint exists yet; show where it WILL come from.
            resume_from = f"checkpoints/{exp_name_of(substages[idx - 1])}/nn/mimic.pth"
        env_cfg.write_text(ENV_TMPL.format(
            stage=ss['suffix'], active=active, num_envs=args.num_envs,
            datasub=yaml_sub_list(ss['sources']), bodies=yaml_sub_list(ss['bodies']),
            pair_weights_line=pair_weights_line, counts_line=counts_line,
            mask_dead_envs=mask_dead, num_obs=num_obs,
            betas_file=args.betas_file, body_norm=body_norm, heights_line=heights_line,
            use_transformer_obs=use_transformer_obs))
        train_cfg.write_text(TRAIN_TMPL.format(
            stage=ss['suffix'], active=active, exp_name=exp_name,
            save_frequency=args.save_frequency, resume_from=resume_from,
            mask_dead_envs=mask_dead, network_name=network_name))

        print(f"\n[curriculum] === substage {idx + 1}/{len(substages)} "
              f"[s{ss['suffix']} {ss['phase']} +sub{ss['new']}] active={active} "
              f"live_pairs={len(ss['live'])} budget(min/pat/cap={min_e}/{pat}/{smax}) "
              f"exp={exp_name} resume={resume_from} ===", flush=True)
        # Self-describing substage block: dump the exact configs it runs into the
        # log so you never have to go find the cfg files to know what ran.
        if args.echo_configs:
            for label, cfg_path in (("env", env_cfg), ("train", train_cfg)):
                print(f"[curriculum] ----- {label} cfg ({rel(cfg_path)}) -----", flush=True)
                print(cfg_path.read_text(), flush=True)
            if use_weights:
                nlive = sum(v > 0 for v in weights.values())
                print(f"[curriculum] ----- pair weights ({rel(weights_file)}): "
                      f"{nlive} live / {len(weights)} pairs, {len(weights) - nlive} masked "
                      f"-----", flush=True)
            print(f"[curriculum] ----- end substage {idx + 1} configs -----", flush=True)
        if args.dry_run:
            extra = (f", {rel(weights_file)} ({len(weights)} pairs, "
                     f"{sum(v > 0 for v in weights.values())} live)" if use_weights
                     else " (no weights file)")
            print(f"  wrote {rel(env_cfg)}, {rel(train_cfg)}{extra}", flush=True)
            continue

        log_path = work / f"substage_s{ss['suffix']}.log"
        epochs_run, exited = run_stage(rel(env_cfg), rel(train_cfg), exp_name, log_path,
                                       args, min_e, pat, smax)
        ckpt = latest_checkpoint(exp_name)
        if ckpt is None:
            print(f"[curriculum] ERROR: substage {idx + 1} produced no checkpoint "
                  f"(exited_on_own={exited}). Aborting; inspect {log_path}.", flush=True)
            sys.exit(1)

        if use_counts and counts_file.exists():
            # MEASURED exposure: accumulate the env's true realized sample counts.
            realized = json.loads(counts_file.read_text())
            for k, c in realized.items():
                exposure[k] = exposure.get(k, 0.0) + float(c)
            # Leak report: any masked (weight 0) pair the env still sampled.
            leaked = {k: realized[k] for k in realized
                      if weights.get(k, 0.0) == 0.0 and realized[k] > 0}
            total = sum(realized.values()) or 1
            if leaked:
                nleak = sum(leaked.values())
                print(f"[curriculum] LEAK substage {idx + 1}: {len(leaked)} masked "
                      f"pairs drawn {nleak}x ({100.0 * nleak / total:.2f}% of draws) "
                      f"via fallback -> {leaked}", flush=True)
            else:
                print(f"[curriculum] no leaks substage {idx + 1} "
                      f"({total} draws, all on live pairs)", flush=True)
        elif use_weights:
            if use_counts:
                print(f"[curriculum] WARNING: measured exposure requested but no counts "
                      f"file at {rel(counts_file)}; using the estimate instead.", flush=True)
            update_exposure(exposure, active, weights, epochs_run)
        prev_ckpt = str(ckpt)
        state_path.write_text(json.dumps(
            {"next_substage": idx + 1, "exposure": exposure, "last_ckpt": prev_ckpt}, indent=2))
        print(f"[curriculum] substage {idx + 1} done: {epochs_run} epochs, ckpt {rel(ckpt)}", flush=True)

    print("[curriculum] all substages complete." if not args.dry_run
          else "[curriculum] dry-run complete (configs generated, nothing launched).", flush=True)


if __name__ == "__main__":
    main()
