#!/usr/bin/env python3
"""Generate the source-teacher DISTILLATION configs (env + train), two variants.

Distills the body-conditioned transformer source-teachers into ONE student via
InterMimic_All (teacher selected per env by source subid; see intermimic_all.py).
Both variants share the target body set (held-out bodies excluded, sub121 dropped)
and differ only in which SOURCES' motions -- and therefore which teachers -- feed
the student:

  noheldout : 13 non-held-out sources {1,2,3,5,6,7,8,9,11,12,14,15,17}
  no14      : all 17 sources except sub14 (corrupt-source suspect) -> 16 sources

Writes:
  data/cfg/omomo_all_source_xf_aug_{variant}.yaml            (env)
  data/cfg/train/rlg/omomo_all_source_xf_aug_{variant}.yaml  (student/DAgger)

The teacher checkpoints must first be collected with collect_source_teachers.py
into checkpoints/teachers/source_xf_aug_{variant}/sub{S}.pth.

IMPORTANT (smoke-test-sensitive, can only be verified on the cluster):
  * numObsRetarget is set to the transformer teacher's 6524; if the student's
    retarget obs differs the buffer alloc / model build errors LOUDLY at startup.
  * motion_file_retarget (OMOMO_retarget) must contain the chosen sources' clips.
  * This is the FIRST distill from TRANSFORMER teachers -- the vmap teacher-query
    path (intermimic_all.py) was only ever run with MLP teachers.
"""
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[1]
CFG = REPO / "isaacgym/src/intermimic/data/cfg"

VARIANTS = {
    "noheldout": [1, 2, 3, 5, 6, 7, 8, 9, 11, 12, 14, 15, 17],
    "no14":      [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 16, 17],
}


def subject_bodies():
    """The exact target body set the teachers train on (13 real + 39 synth)."""
    env = yaml.safe_load(open(CFG / "omomo_teacher_src2_xf_aug.yaml"))["env"]
    return env["subjectBodies"]


def sub_list(nums):
    return "[" + ", ".join(f"'sub{n}'" for n in nums) + "]"


ENV_TMPL = """\
# AUTO-GENERATED by scripts/generate_source_distill_cfgs.py -- source-teacher
# distillation, variant '{variant}'. One body-conditioned transformer student
# imitates the per-source transformer teachers (selected by source subid).
# Sources: {sources}
env:
  numEnvs: 4096
  envSpacing: 2
  episodeLength: 300
  isFlagrun: False
  enableDebugVis: False
  playdataset: False
  projtype: "None"
  saveImages: False
  initVel: False
  moreRigid: False
  pdControl: True
  powerScale: 1.0
  controlFrequencyInv: 2
  stateInit: "Hybrid"
  rolloutLength: 300
  hybridInitProb: 0.5
  dataFPS: 30
  dataFramesScale: 1
  ballSize: 1.
  numObs: 6524            # transformer TEACHER obs (4-horizon, body-conditioned)
  numObsRetarget: 6524    # transformer STUDENT obs (smoke-test-sensitive; see header)
  useTransformerObs: True
  motion_file: InterAct/OMOMO_new
  motion_file_retarget: InterAct/OMOMO_retarget
  robotType: "smplx/omomo.xml"
  objectDensity: 200
  dataSub: {datasub}
  subjectBodies: {bodies}
  betas_file: scripts/omomo_betas_neutral_aug.npz
  bodyNormalizedReward: true
  subjectHeightsFile: scripts/synthetic_heights.json
  rewardTerms:
    pose:
      enable: true
      lambda: 0.02
  localRootObs: False
  keyBodies: ["L_Hip", "L_Knee", "L_Ankle", "L_Toe", "R_Hip", "R_Knee", "R_Ankle", "R_Toe", "Torso", "Spine", "Chest", "Neck", "Head", "L_Thorax", "L_Shoulder", "L_Elbow", "L_Wrist", "R_Thorax", "R_Shoulder", "R_Elbow", "R_Wrist"]
  contactBodies: ["L_Hip", "L_Knee", "L_Ankle", "L_Toe", "R_Hip", "R_Knee", "R_Ankle", "R_Toe", "Torso", "Spine", "Chest", "Neck", "Head", "L_Thorax", "L_Shoulder", "L_Elbow", "L_Wrist", "R_Thorax", "R_Shoulder", "R_Elbow", "R_Wrist", "L_Index3", "L_Middle3", "L_Pinky3", "L_Ring3","L_Thumb3","R_Index3", "R_Middle3", "R_Pinky3", "R_Ring3","R_Thumb3"]
  terminationHeight: 0.15
  enableEarlyTermination: True
  physicalBufferSize: 3
  teacherPolicy: checkpoints/teachers/source_xf_aug_{variant}
  teacherPolicyCFG: intermimic/data/cfg/train/rlg/omomo_teacher_src2_xf_aug.yaml

  asset:
    assetRoot: "intermimic/data/assets"

  plane:
    staticFriction: 0.9
    dynamicFriction: 0.9
    restitution: 0.7

  rewardWeights:
    p: 30.
    r: 2.5
    pv: 0.
    rv: 0.
    op: 5.0
    or: 0.1
    opv: 0.1
    orv: 0.
    ig: 5.
    cg_hand: 5.
    cg_other: 5.
    cg_all: 3.
    eg1: 0.00002
    eg2: 0.00002
    eg3: 0.000000001

sim:
  substeps: 2
  physx:
    num_threads: 4
    solver_type: 1
    num_position_iterations: 4
    num_velocity_iterations: 1
    contact_offset: 0.02
    rest_offset: 0.0
    bounce_threshold_velocity: 0.2
    max_depenetration_velocity: 100.0
    default_buffer_size_multiplier: 20.0
    max_gpu_contact_pairs: 34603008
  flex:
    num_inner_iterations: 10
    warm_start: 0.25
"""

TRAIN_TMPL = """\
params:
  seed: -1

  algo:
    name: intermimic

  model:
    name: intermimic

  network:
    name: intermimic_transformer
    separate: True

    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: -2.9
        fixed_sigma: True
        learn_sigma: False

    mlp:
      units: [256]
      activation: relu
      d2rl: False
      initializer:
        name: default
      regularizer:
        name: None

  load_checkpoint: False

  config:
    name: mimic
    # AUTO-GENERATED source-teacher distillation student, variant '{variant}'.
    full_experiment_name: smplx_student_source_xf_aug_{variant}
    env_name: rlgpu
    multi_gpu: False
    ppo: True
    mixed_precision: False
    normalize_input: True
    normalize_value: False
    reward_shaper:
      scale_value: 1
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 2e-5
    lr_schedule: constant
    score_to_win: 20000
    max_epochs: 100000
    save_best_after: 500
    save_frequency: 500
    print_stats: True
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: False
    e_clip: 0.2
    horizon_length: 16
    minibatch_size: 8192
    mini_epochs: 6
    critic_coef: 5
    clip_value: False
    seq_len: 4
    bounds_loss_coef: 10
    expert_loss_coef: 1
    enable_eps_greedy: False
    save_intermediate: False
    resume_from: 'None'
"""


def main():
    bodies = sub_list(subject_bodies())
    for variant, sources in VARIANTS.items():
        env_txt = ENV_TMPL.format(variant=variant, sources=sources,
                                  datasub=sub_list(sources), bodies=bodies)
        train_txt = TRAIN_TMPL.format(variant=variant)
        env_path = CFG / f"omomo_all_source_xf_aug_{variant}.yaml"
        train_path = CFG / "train/rlg" / f"omomo_all_source_xf_aug_{variant}.yaml"
        env_path.write_text(env_txt)
        train_path.write_text(train_txt)
        # validate both parse
        assert yaml.safe_load(open(env_path))["env"]["numObs"] == 6524
        assert yaml.safe_load(open(train_path))["params"]["config"]["expert_loss_coef"] == 1
        print(f"[{variant}] {len(sources)} sources -> "
              f"{env_path.relative_to(REPO)} + {train_path.relative_to(REPO)}")


if __name__ == "__main__":
    main()
